FROM gliderlabs/alpine:3.3

# Install Python Pip and the Robot framework
RUN apk-install bash py-pip firefox xvfb dbus chromium-chromedriver && \
    pip install --upgrade pip && \
    pip install robotframework robotframework-selenium2library selenium robotframework-xvfb && \
    python --version 
